import streamlit as st
import pandas as pd
import numpy as np
from streamlit_extras.switch_page_button import switch_page
 
st.set_page_config(initial_sidebar_state='collapsed',layout='wide')
 
st.markdown(
    """
    <center>
        <h1 style="font-size: 3rem;">Business Data Details</h1>
    </center>
    """,
    unsafe_allow_html=True,
)

def csv_file(uploaded_file):
    with open(uploaded_file.name, 'wb') as f:
        f.write(uploaded_file.getbuffer())
    st.success(f"CSV file '{uploaded_file.name}' saved successfully.")

col1,col2=st.columns(2)
 
with col1:
    st.header("Project Details")
    st.markdown(
        """
        It is a project aimed at generating synthetic business datasets with 15 columns, encompassing various numeric and categorical variables.
        The project leverages Python programming along with the Faker library to produce realistic yet fabricated data resembling real-world businesses.
        
        **Objective**: The primary goal of the project is to create synthetic business datasets that mimic real-world scenarios for analytical purposes, such as testing machine learning algorithms, data visualization techniques, and database management systems.
        
        **Dataset Attributes**: The synthetic dataset comprises 15 columns, including Business Name, Category, Revenue, Expenses, Profit, Profit Margin, City, State, ZipCode, Latitude, Longitude, Is Open, Wifi, Outdoor Seating, Delivery.
        
        **Tools and Libraries**: The project utilizes Python programming language along with the Faker library for generating synthetic data. Additionally, the pandas library is employed for data manipulation and analysis.
        
        **Implementation**: The implementation involves writing Python code to generate synthetic business data using the Faker library. The code includes functions to create realistic business names, categories, ratings, and other attributes. Pandas DataFrame is utilized to structure the generated data into a tabular format for further analysis.
        
        **Usage**: The synthetic business dataset generated by "SynthBizGen-15" can be utilized for various purposes, including testing and benchmarking machine learning models, evaluating data visualization techniques, simulating database management scenarios, and educational purposes.
        
        """
    )
 
with col2:
    st.header("Input User data")
    uploaded_file=st.file_uploader("Choose a csv file: ",type="csv")
    if uploaded_file is not None:
        st.info("File uploaded successfully.")
       
        csv_file(uploaded_file)
       
        button=st.button("SUBMIT")
        if button:
            switch_page("first")